spring:
  banner:
    image:
      location: duke.png

# Configurations to use H2 database:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true

# Configurations to use MySQL database:
  datasource:
    url: jdbc:mysql://localhost:3306/guitar_tech
    username: root
    password: baxacuaanh0751961
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
    show-sql: true